echo "fans[0].name :",fans[0].name
echo "fans[1].name :",fans[1].name
echo "fans[2].name :",fans[2].name
echo "fans[3].name :",fans[3].name
;echo "fans[4].name :",fans[4].name
;echo "fans[5].name :",fans[5].name
;echo "fans[6].name :",fans[6].name
;echo "fans[7].name :",fans[7].name
;echo "fans[8].name :",fans[8].name
