; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool on Wed Sep 19 2018 19:05:58 GMT+0100 (British Summer Time)
M83            ; relative extruder moves
G1 E-10 F3600  ; retract 10mm of filament
; G10 ; set G10?
M98 P"/sys/move/park.g"

